config/routes.rb
TwitterMock::Application.routes.draw do
  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  root :to => 'bweets#index'
  resources :users, only: [:new, :create]
  resources :bweets, only: [:index, :create]
  post "bweets/create"

end

app/models/bweet.rb
class Bweet < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :description
  default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bweet
  validates_presence_of :name, :mail, :password_digest
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bweets_controller.rb
class BweetsController < ApplicationController
  def index
    if request.xhr?
      session[:bweet_page] += 1
      @bweets = Bweet.limit(10).offset(10 * session[:bweet_page])
      render partial: 'bweets', collections: @bweets
    else
      session[:bweet_page] = 0
      @bweets = Bweet.limit(10)
      @user = User.find_by_id(session[:user_id])
    end
  end

  def create
    @bweet = Bweet.new(bweet_params)
    @bweet.user_id = session[:user_id]
    respond_to do |format|
      if @bweet.save
        @bweets = Bweet.limit(10)
        format.html { render partial: 'bweets', collections: @bweets }
      else
        redirect_to root_url, notice: 'Submit Error!'
      end
    end
  end

  private
  def bweet_params
    params.permit(:description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'You are signed in!'
    else
      redirect_to root_url, notice: 'Invalid UseName / Password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are signed out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new  
    @user = User.new
  end  
  
  def create
    @user = User.new(user_params)
    if @user.save
      user = User.find_by_name(@user.name)
      session[:user_id] = user.id
      icon = params[:user][:icon]
      File.open("./public/icons/#{user.id}.jpg", "wb") { |f| f.write(icon.read) }
      redirect_to root_url, notice: "Your account is created!"  
    else  
      render "new", notice: "Your account isn't created!"
    end  
  end

  private
    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bweets_helper.rb
module BweetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bweets/_bweets.html.erb
<% @bweets.each do |bweet| %>
  <fieldset>
    <legend>
      <h2>
        <%= image_tag("/icons/#{bweet.user_id}.jpg", alt: :icon, size: "24x24") %>
        <%= bweet.user.name %>
      </h2>
    </legend>
    <p><%= bweet.description %></p>
    <h6><%= bweet.created_at %></h6>
  </fieldset>
<% end %>

app/views/bweets/_form.html.erb
<fieldset>
  <legend>Bweet</legend>
  <textarea id="bweet_description"></textarea><br>
  <button type="submit" id="bweet_button">Bweet</button>
</fieldset>

app/views/bweets/index.html.erb
<div id='wrap'>
  <div id='header'>
    <% if flash[:notice] %>
      <p class='notice'><%= flash[:notice] %></p>
    <% end %>
  </div><!-- /header -->

  <div id='innner'>
    <div id='sideWrap'>
      <% if session[:user_id].nil? %>
        <%= render 'sessions/form' %>
        <%= link_to 'Sign up', new_user_path %>
      <% else %>
        <h4>UserName<br><%= @user.name %></h4>
        <%= image_tag("/icons/#{@user.id}.jpg", alt: :icon, size: "64x64") %><br>
        <%= link_to 'Sign out', sessions_destroy_path %>
        <%= render 'bweets/form' %>
      <% end %>
    </div><!-- /sideWrap -->
    <div id='mainWrap'>
      <h1>Bweets</h1>
      <div id='bweets'>
        <%= render partial: "bweets", collections: @bweets %>
      </div>
      <button type="submit" id="more_show">More Show 10 Bweets</button>
    </div><!-- /mainWrap -->
  </div><!-- inner -->
  <div class="clear"></div>
</div><!-- /wrap -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterMock</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Welcome New User!</h1>
<div>
  <%= form_for @user do |f| %>
    <% if @user.errors.any?%>  
      <div class="error_messages">
        <ul>  
          <% @user.errors.full_messages.each do |msg| %>  
            <li><%= msg %></li>  
          <% end %>  
        </ul>
      </div>  
    <% end %>  
    <fieldset>
      <legend>Input your data</legend>
      <div>
      <%= f.label :name %>
      <%= f.text_field :name, size: 20 %>
      </div>
      <div>
      <%= f.label :mail %>
      <%= f.text_field :mail, size: 30 %>
      </div>
      <div>
      <%= f.label :password %>
      <%= f.password_field :password, size: 20 %>
      </div>
      <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, size: 20 %>
      </div>
      <div>
      <%= f.label :icon %>
      <%= f.file_field :icon %>
      </div>
      <%= f.submit %>
    </fieldset>
  <% end %>
</div>